dist: trusty
language: rust
rust:
  - stable
  - nightly
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - libdbus-1-dev
      - libgoogle-perftools-dev
      - pandoc
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
env:
  - RUSTFLAGS="-D warnings"
jobs:
  include:
    - stage: docs
    script: pandoc README.md blocks.md themes.md -s -t man -o manpage
    - stage: test
    script: cargo build
    script: cargo test